name: green-gesture-prod
services:
  prodDB:
    image: postgres:15-alpine
    container_name: green-db
    env_file:
      - .env.production
    environment:
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - prodDB:/var/lib/postgresql/data

  server:
    image: mickael01/green-gesture-server:latest
    container_name: green-server
    depends_on:
      prodDB:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:8000}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - SERVER_HOST=${SERVER_HOST:-localhost}
      - SERVER_PORT=${SERVER_PORT:-4000}
      - DB_HOST=${DB_HOST:-prodDB}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - DB_NAME=${DB_NAME:-postgres}
      - DB_PORT=${DB_PORT:-5432}
    healthcheck:
      test: "curl --fail --request GET -H 'content-type:application/json' --url 'http://localhost:4000/graphql?query=%7B__typename%7D'"
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    image: mickael01/green-gesture-client:latest
    container_name: green-client
    env_file:
      - .env.production
    environment:
      - VITE_GRAPHQL_API_URL=${VITE_GRAPHQL_API_URL:-http://localhost:4000}
      - VITE_PUBLIC_KEY_UPLOADCARE=${VITE_PUBLIC_KEY_UPLOADCARE}
      - VITE_PUBLIC_STRIPE_KEY=${VITE_PUBLIC_STRIPE_KEY}

  nginx:
    image: nginx:1.21.3
    container_name: green-nginx
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_healthy
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

  stripe-service:
    image: mickael01/green-gesture-microservice-stripe:latest
    container_name: green-stripe-service
    restart: always
    env_file:
      - .env.production
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
    ports:
      - 4002:4002
    volumes:
      - ./stripe-service/index.js:/app/index.js

  # discord-bot:
  #   image: samwildcode/discord-bot
  #   depends_on:
  #     nginx:
  #       condition: service_started
  #   environment:
  #     - BOT_TOKEN=${BOT_TOKEN:-}
  #     - CHANNEL_ID=${CHANNEL_ID:-}
  #   command: "npm run send-message 'Green Gesture Production environment has been updated ! See you here : https://neumann2.wns.wilders.dev/'"

volumes:
  prodDB:
